language: node_js

cache:
  directories:
    - "Ëœ/.npm"

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '10'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g npm@latest

install:
  - npm ci

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
  on:
    branch: master
    repo: settlemint/amqplib-mocks
